### ISSUE TITLE
Why calculating the Hessian matrix in this way?

### ISSUE THREAD

**Issue by XiaLiPKU** [Louisvh/cycle_consistent_INR#2]
https://github.com/Louisvh/cycle_consistent_INR/blob/9d8ef3a14fc973523cef8aebee02c79c2b1ed5d3/utils/general.py#L88
if a coordinate is of shape [3], then the Jacobian matrix will be of shape [3 x 3], and the Hessian matrix be of 3 * [3 x 3].
Why do you choose to calculate the Hessian matrix in this form? I don't understand it from Eq. 9, may you kindly explain a bit?

**Comment by Louisvh** [comment]
We calculate it like this mostly for convenience. By first calculating the local first order derivative with the inverse jacobian, we compress the relevant derivatives back into a 3x1 vector, i.e. the derivatives of x/y/z when we vary the input along the single dimension `coordmarks_S - co_BFS`; we don't care about all of the other dimensions, so we don't need to keep track of them (and we don't need to calculate them). From there on, we can reuse the same code to get the second order derivatives as well. You're right that calling the variable "hessian" in the code was perhaps a bit confusing in retrospect (as that variable doesn't actually contain the full hessian; just the parts we care about). I hope that clears it up!
