### ISSUE TITLE
Question about the mask

### ISSUE THREAD

**Issue by mlyang23** [Louisvh/cycle_consistent_INR#3]
Hello, I would like to know how you generate the mask for the 4DCT dataset. I am not very proficient in using lungmask, could you please provide me with the specific code? Thank you.

**Comment by Louisvh** [comment]
You can install the lungmask package as described [here](https://github.com/JoHof/lungmask#installation). The usage examples (both for using it as a command line tool and for using it as a python package) can be found [here](https://github.com/JoHof/lungmask#usage).

**Comment by mlyang23** [comment]
Thank you for your response. I still have some confusion. It seems that lungmask has requirements for the data range. The 4DCT dataset, such as case1_T00.img, is read as int16 data ranging from 0 to several thousand. I would like to know how you handle them to use the lungmask library. My results seem to be not good. Here is some of my code:

path = 'D:\data_dir\Case8pack\Images\case8_T00.img'

shape = [128, 512, 512]
dtype = np.dtype(np.int16)
with open(path, "rb") as f:
    data = np.fromfile(f, dtype)
data = data.reshape(shape)

data_float32 = data.astype(np.float32)
inferer = LMInferer(modelname="LTRCLobes")

data_normal = data_float32 / np.max(data) * 2048 - 1024
data_normal = sitk.GetImageFromArray(data_normal)
segmentation = inferer.apply(data_normal)

Thanks for your patience :)
